# Generated by Django 4.1.3 on 2024-10-20 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krome', '0002_rename_profile_athlete'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='athlete',
            field=models.ImageField(default=1, upload_to='', verbose_name='User Owner'),
        ),
    ]
