# Generated by Django 4.1.3 on 2024-10-20 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krome', '0003_athlete_athlete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete',
            name='athlete',
            field=models.IntegerField(default=1, verbose_name='ID'),
        ),
    ]
