# Generated by Django 4.1.3 on 2024-10-20 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('krome', '0004_alter_athlete_athlete'),
    ]

    operations = [
        migrations.RenameField(
            model_name='athlete',
            old_name='members',
            new_name='member',
        ),
    ]
