# Generated by Django 4.1.3 on 2024-10-21 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('krome', '0007_athlete_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='athlete',
            name='athlete',
        ),
    ]
