# Generated by Django 4.1.3 on 2024-10-21 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('krome', '0008_remove_athlete_athlete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='athlete',
            name='member',
        ),
    ]
